export type MarqueePackage = {
  id: string;
  name: string;
  tier: 'General' | 'VIP' | 'VVIP' | 'Premium' | 'Ultra VIP';
  price: string;
  priceValue: number;
  venue: string;
  description: string;
  includes: string[];
  capacity?: string;
  image: string;
};

export type EventItem = {
  id: string;
  name: string;
  date: string;
  time: string;
  venue: string;
  location: string;
  category: 'Race Day' | 'Party' | 'Fashion' | 'Concert' | 'Lifestyle' | 'After Party';
  description: string;
  price: string;
  priceValue: number;
  highlights: string[];
  image: string;
};

export type AccommodationItem = {
  id: string;
  name: string;
  type: 'Guest House' | 'Boutique Hotel' | 'Luxury Hotel' | 'Villa' | 'Apartment';
  area: string;
  pricePerNight: string;
  priceValue: number;
  rating: number;
  description: string;
  amenities: string[];
  distanceToVenue: string;
  image: string;
};

export type TransportItem = {
  id: string;
  name: string;
  type: 'Shuttle' | 'Chauffeur' | 'Helicopter' | 'Luxury Car';
  price: string;
  description: string;
  features: string[];
  image: string;
};

export type ConciergeService = {
  id: string;
  name: string;
  category: 'Styling' | 'Grooming' | 'Photography' | 'Security' | 'Personal Assistant' | 'Catering';
  price: string;
  description: string;
  features: string[];
  image: string;
};

// MARQUEES - 31 Total
export const marquees: MarqueePackage[] = [
  {
    id: 'm1',
    name: 'Hollywoodbets Premium Marquee',
    tier: 'Ultra VIP',
    price: 'By Invitation',
    priceValue: 10000,
    venue: 'VIP Village (Site WP)',
    description: 'The official Hollywoodbets marquee at the heart of the VIP Village. Situated at the centre of Greyville Racecourse, it offers a sophisticated atmosphere with Mzansi-inspired gourmet cuisine, bespoke cocktails, and live Afro-pop and Amapiano performances.',
    includes: [
      'Exclusive marquee access',
      'Gourmet Mzansi-inspired cuisine',
      'Bespoke cocktail bar',
      'Live entertainment (Afro-pop & Amapiano)',
      'Premium open bar',
      'VIP parking',
    ],
    image: 'https://api.a0.dev/assets/image?text=hollywoodbets+premium+marquee+durban+july+2025+luxury+gold+decor+racecourse&aspect=16:9&seed=1001',
  },
  {
    id: 'm2',
    name: 'Beluga Hospitality Finish Line VIP Lounge',
    tier: 'Ultra VIP',
    price: 'From R8,500',
    priceValue: 8500,
    venue: 'VIP Village (Site DC)',
    description: 'Beluga\'s iconic Finish Line VIP Lounge returns with legendary hospitality. Prime positioning right at the finish line with unobstructed views of every race, signature cocktails, and five-course gourmet dining.',
    includes: [
      'Finish line viewing position',
      'Beluga signature cocktails & premium open bar',
      'Seafood & sushi platters',
      'Five-course gourmet dining',
      'Champagne on arrival',
      'Live DJ entertainment',
      'Personal betting concierge',
      'VIP valet parking',
    ],
    capacity: 'Limited',
    image: 'https://api.a0.dev/assets/image?text=beluga+finish+line+vip+lounge+durban+july+seafood+champagne+luxury+racecourse&aspect=16:9&seed=1002',
  },
  {
    id: 'm3',
    name: 'The Opulent Experience Marquee',
    tier: 'VVIP',
    price: 'From R6,500',
    priceValue: 6500,
    venue: 'VIP Village (Site D)',
    description: 'A curated luxury experience blending opulence with South African flair. Expect designer decor, premium hospitality, gourmet food, and an all-inclusive bar experience in the heart of the VIP Village.',
    includes: [
      'All-inclusive food and drinks',
      'Premium open bar',
      'Gourmet plated meals',
      'Designer decor and ambiance',
      'Live entertainment',
      'Fashion moments',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=opulent+experience+marquee+durban+july+luxury+elegant+gold+decor+vip&aspect=16:9&seed=1003',
  },
  {
    id: 'm4',
    name: 'Chaise Lounge',
    tier: 'VVIP',
    price: 'From R5,500',
    priceValue: 5500,
    venue: 'VIP Village (Site DD1)',
    description: 'An intimate and chic marquee experience offering refined hospitality. Chaise Lounge brings sophisticated decor, craft cocktails, and a curated music experience for the discerning guest.',
    includes: [
      'Premium marquee access',
      'Craft cocktail bar',
      'Gourmet dining experience',
      'Curated music and DJs',
      'Chic lounge seating',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=chaise+lounge+marquee+durban+july+chic+sophisticated+intimate+lounge+decor&aspect=16:9&seed=1004',
  },
  {
    id: 'm5',
    name: 'Durban Tourism Hospitality',
    tier: 'VIP',
    price: 'From R4,500',
    priceValue: 4500,
    venue: 'VIP Village (Sites A1 & A2)',
    description: 'The official Durban Tourism marquee celebrating the city\'s vibrant culture. Features local cuisine, Durban-inspired cocktails, and entertainment showcasing the best of eThekwini.',
    includes: [
      'All-inclusive hospitality',
      'Local Durban cuisine',
      'Premium drinks package',
      'Live entertainment',
      'Cultural showcases',
      'Race day programme',
    ],
    image: 'https://api.a0.dev/assets/image?text=durban+tourism+marquee+durban+july+colorful+zulu+culture+hospitality&aspect=16:9&seed=1005',
  },
  {
    id: 'm6',
    name: 'Halisi Afrique Hospitality Marquee',
    tier: 'VVIP',
    price: 'From R6,000',
    priceValue: 6000,
    venue: 'VIP Village (Site H)',
    description: 'Step into the vibrant energy of Halisi Afrique, where striking decor meets eclectic fashion and exotic flavours. A high-energy celebration of local culture and homegrown talent.',
    includes: [
      'All-inclusive premium experience',
      'Gourmet food and exotic flavours',
      'Premium drinks and cocktails',
      'Luxury pampering experience',
      'Live entertainment and DJs',
      'Afro-luxury decor',
      'Fashion showcase',
    ],
    image: 'https://api.a0.dev/assets/image?text=halisi+afrique+marquee+durban+july+african+luxury+vibrant+decor+exotic+food&aspect=16:9&seed=1006',
  },
  {
    id: 'm7',
    name: 'Gushima Lifestyle Marquee',
    tier: 'VIP',
    price: 'From R4,000',
    priceValue: 4000,
    venue: 'VIP Village (Site K)',
    description: 'The Gushima Lifestyle Marquee brings together music, fashion, and culture in a vibrant setting. A premium lifestyle experience celebrating Mzansi\'s creative spirit.',
    includes: [
      'Premium marquee access',
      'All-inclusive food and drinks',
      'Live music and DJs',
      'Fashion moments',
      'Lifestyle activations',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=gushima+lifestyle+marquee+durban+july+vibrant+music+fashion+culture&aspect=16:9&seed=1007',
  },
  {
    id: 'm8',
    name: 'OMODA Royalty Marquee',
    tier: 'VVIP',
    price: 'From R7,000',
    priceValue: 7000,
    venue: 'VIP Village (Site F5)',
    description: 'The OMODA Royalty Marquee offers a regal hospitality experience. Expect royal treatment with premium service, gourmet cuisine, and an elegant atmosphere.',
    includes: [
      'Royal-themed hospitality',
      'Premium open bar',
      'Gourmet multi-course dining',
      'Live entertainment',
      'Fashion showcase',
      'VIP parking',
      'Gift bags',
    ],
    image: 'https://api.a0.dev/assets/image?text=omoda+royalty+marquee+durban+july+regal+gold+crown+luxury+elegant&aspect=16:9&seed=1008',
  },
  {
    id: 'm9',
    name: 'Ambrosia Haven',
    tier: 'VIP',
    price: 'From R4,500',
    priceValue: 4500,
    venue: 'VIP Village (Site F6)',
    description: 'Ambrosia Haven delivers a sensory feast with exquisite food, premium drinks, and immersive entertainment. A haven of indulgence in the VIP Village.',
    includes: [
      'All-inclusive experience',
      'Gourmet food stations',
      'Premium open bar',
      'Live entertainment',
      'Lounge seating',
      'Photo opportunities',
    ],
    image: 'https://api.a0.dev/assets/image?text=ambrosia+haven+marquee+durban+july+indulgent+food+premium+drinks+elegant&aspect=16:9&seed=1009',
  },
  {
    id: 'm10',
    name: 'Global Events Marquee',
    tier: 'VIP',
    price: 'From R4,000',
    priceValue: 4000,
    venue: 'VIP Village (Site N)',
    description: 'Global Events brings international flair to the Durban July VIP Village. A cosmopolitan marquee experience with world-class hospitality and entertainment.',
    includes: [
      'Premium marquee access',
      'All-inclusive food and drinks',
      'International cuisine',
      'Live entertainment',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=global+events+marquee+durban+july+cosmopolitan+international+luxury&aspect=16:9&seed=1010',
  },
  {
    id: 'm11',
    name: 'Empire Marquee',
    tier: 'VIP',
    price: 'From R3,500',
    priceValue: 3500,
    venue: 'Golf Course (Cabana 1)',
    description: 'The Empire Marquee offers a vibrant golf course setting with energetic entertainment, premium drinks, and a party atmosphere that keeps the energy high all day.',
    includes: [
      'Golf course marquee access',
      'Premium drinks package',
      'Food stations',
      'Live DJs and entertainment',
      'Big screen race viewing',
      'Tote betting facilities',
    ],
    image: 'https://api.a0.dev/assets/image?text=empire+marquee+durban+july+golf+course+party+vibrant+energy&aspect=16:9&seed=1011',
  },
  {
    id: 'm12',
    name: 'Insync Events Hospitality',
    tier: 'VIP',
    price: 'From R3,500',
    priceValue: 3500,
    venue: 'Golf Course (Site F1)',
    description: 'Insync Events brings a perfectly synchronised marquee experience with top-class sound, lighting, and a hand-picked DJ lineup alongside premium hospitality.',
    includes: [
      'Premium marquee access',
      'All-inclusive food and drinks',
      'Top-class sound and lighting',
      'DJ lineup',
      'Race viewing screens',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=insync+events+marquee+durban+july+dj+sound+lighting+party&aspect=16:9&seed=1012',
  },
  {
    id: 'm13',
    name: 'Saso\'s Brunch Marquee',
    tier: 'VVIP',
    price: 'From R6,500',
    priceValue: 6500,
    venue: 'Golf Course (Site F2)',
    description: 'The star-studded Saso\'s Brunch Marquee returns for its second year. Curated by hip-hop star Lusaso Saso Ngcobo, this immersive celebration of Black excellence features Afro-futuristic fashion and world-class entertainment.',
    includes: [
      'Exclusive brunch experience',
      'Gourmet culinary experiences',
      'Signature cocktail bars',
      'Afro-futuristic fashion moments',
      'World-class live entertainment',
      'Celebrity guest appearances',
      'Premium concierge service',
      'Luxury decor',
    ],
    capacity: '800 guests',
    image: 'https://api.a0.dev/assets/image?text=sasos+brunch+marquee+durban+july+luxury+black+excellence+afro+futuristic+gold&aspect=16:9&seed=1013',
  },
  {
    id: 'm14',
    name: 'True North Holdings with SaintSKN',
    tier: 'VIP',
    price: 'From R4,000',
    priceValue: 4000,
    venue: 'Golf Course (Site F4)',
    description: 'True North Holdings partners with SaintSKN to deliver a refined marquee experience combining wellness luxury with premium race day hospitality.',
    includes: [
      'Premium marquee access',
      'All-inclusive food and drinks',
      'SaintSKN pampering experience',
      'Live entertainment',
      'Wellness activations',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=true+north+saintskn+marquee+durban+july+wellness+luxury+skincare&aspect=16:9&seed=1014',
  },
  {
    id: 'm15',
    name: 'Makubenjalo (Njalo\'s July)',
    tier: 'VIP',
    price: 'From R3,500',
    priceValue: 3500,
    venue: 'Golf Course (Site F7)',
    description: 'Makubenjalo delivers an authentic Mzansi marquee experience. Vibrant energy, local flavours, and entertainment that celebrates South African culture.',
    includes: [
      'Marquee access',
      'All-inclusive food and drinks',
      'Local entertainment and DJs',
      'Cultural celebrations',
      'Race viewing screens',
      'Cash bar upgrade options',
    ],
    image: 'https://api.a0.dev/assets/image?text=makubenjalo+marquee+durban+july+mzansi+vibrant+cultural+celebration&aspect=16:9&seed=1015',
  },
  {
    id: 'm16',
    name: 'Tiger Tiger Marquee',
    tier: 'VIP',
    price: 'From R3,000',
    priceValue: 3000,
    venue: 'Golf Course',
    description: 'The Tiger Tiger Marquee brings its signature party atmosphere to the Durban July golf course precinct. Expect high-energy DJs, premium drinks, and a buzzing social scene.',
    includes: [
      'Marquee access',
      'Premium drinks package',
      'Food stations',
      'Top DJs',
      'Race viewing screens',
      'Party atmosphere',
    ],
    image: 'https://api.a0.dev/assets/image?text=tiger+tiger+marquee+durban+july+party+high+energy+dj+crowd&aspect=16:9&seed=1016',
  },
  {
    id: 'm17',
    name: 'Afrotainment Marquee',
    tier: 'VIP',
    price: 'From R3,500',
    priceValue: 3500,
    venue: 'Golf Course',
    description: 'DJ Tira\'s Afrotainment Marquee is always one of the hottest marquees at the Durban July. Non-stop Gqom, Amapiano, and Afro-house with surprise celebrity performances.',
    includes: [
      'Premium marquee access',
      'All-inclusive food and drinks',
      'Non-stop DJ entertainment',
      'Gqom and Amapiano music',
      'Celebrity appearances',
      'Race viewing screens',
    ],
    image: 'https://api.a0.dev/assets/image?text=afrotainment+dj+tira+marquee+durban+july+gqom+amapiano+party+energy&aspect=16:9&seed=1017',
  },
  {
    id: 'm18',
    name: 'Boomtown General',
    tier: 'General',
    price: 'From R1,093',
    priceValue: 1093,
    venue: 'Boomtown Arena',
    description: 'For 15 years, Boomtown has set the standard for premium outdoor entertainment at the Durban July. The 2026 lineup features Sjava, Cassper Nyovest, and Nasty C.',
    includes: [
      'General entrance to Boomtown',
      'Access to live entertainment stage',
      'Cash bar facilities',
      'Food vendors',
      'Big screen race viewing',
      'Tote betting facilities',
      'Includes Greyville racecourse entry',
    ],
    image: 'https://api.a0.dev/assets/image?text=boomtown+general+durban+july+2025+outdoor+stage+sjava+cassper+crowd&aspect=16:9&seed=1018',
  },
  {
    id: 'm19',
    name: 'Boomtown VIP',
    tier: 'VIP',
    price: 'From R4,025',
    priceValue: 4025,
    venue: 'Boomtown VIP Enclosure',
    description: 'Elevated Boomtown experience with premium open bar, gourmet food buffet, and priority viewing of performances.',
    includes: [
      'VIP Boomtown access',
      'Premium open bar',
      'Gourmet food buffet',
      'Dedicated VIP restrooms',
      'Priority stage viewing area',
      'Race programme',
      'Includes racecourse entry',
    ],
    image: 'https://api.a0.dev/assets/image?text=boomtown+vip+durban+july+2025+premium+bar+elegantly+dressed+guests&aspect=16:9&seed=1019',
  },
  {
    id: 'm20',
    name: 'Boomtown VVIP',
    tier: 'VVIP',
    price: 'From R5,175',
    priceValue: 5175,
    venue: 'Boomtown VVIP Lounge',
    description: 'The ultimate Boomtown experience. Exclusive VVIP lounge with top-shelf spirits, champagne service, gourmet plated meals, and personal waitstaff.',
    includes: [
      'Exclusive VVIP lounge access',
      'Top-shelf premium open bar',
      'Champagne service',
      'Gourmet plated meal service',
      'Private restrooms',
      'Personal waitstaff',
      'Celebrity lounge access',
      'Betting vouchers',
    ],
    image: 'https://api.a0.dev/assets/image?text=boomtown+vvip+lounge+durban+july+champagne+luxury+exclusive&aspect=16:9&seed=1020',
  },
  {
    id: 'm21',
    name: 'Boomtown VVIP Private Tables',
    tier: 'Ultra VIP',
    price: 'From R6,325 pp',
    priceValue: 6325,
    venue: 'Boomtown VVIP',
    description: 'Private tables for groups of 10 or 20 in the VVIP section. The most exclusive Boomtown experience with personal hosts and premium service.',
    includes: [
      'Private reserved table (10 or 20 guests)',
      'Dedicated personal host',
      'Top-shelf premium open bar',
      'Champagne on ice',
      'Multi-course gourmet dining',
      'Private security',
      'VIP parking passes',
      'Betting vouchers',
    ],
    capacity: 'Tables of 10 or 20',
    image: 'https://api.a0.dev/assets/image?text=boomtown+private+vip+table+durban+july+champagne+bottles+luxury&aspect=16:9&seed=1021',
  },
  {
    id: 'm22',
    name: 'Pegasus Lounge',
    tier: 'Ultra VIP',
    price: 'From R8,280',
    priceValue: 8280,
    venue: 'Boomtown Trackside',
    description: 'In its fifteenth year, the Pegasus Lounge has cemented its status as the premier hospitality experience at the Durban July. Ultra-premium open bar and Chef\'s Table dining.',
    includes: [
      'Pegasus Lounge trackside access',
      'Ultra-premium open bar',
      'Five-course Chef\'s Table menu',
      'Champagne welcome reception',
      'Celebrity appearances',
      'Fashion show viewing',
      'Personal concierge',
      'Valet parking',
      'Luxury gift bag',
    ],
    image: 'https://api.a0.dev/assets/image?text=pegasus+lounge+durban+july+2025+luxury+gold+decor+fine+dining+trackside&aspect=16:9&seed=1022',
  },
  {
    id: 'm23',
    name: 'JVS Agencies Marquee',
    tier: 'Premium',
    price: 'From R5,500',
    priceValue: 5500,
    venue: 'Grandstand (Subway)',
    description: 'The JVS Agencies marquee in the Grandstand Subway section offers a premium indoor experience with excellent views, gourmet dining, and premium bar service.',
    includes: [
      'Grandstand marquee access',
      'Premium open bar',
      'Gourmet dining',
      'Race viewing',
      'VIP restrooms',
      'Race programme and betting guide',
    ],
    image: 'https://api.a0.dev/assets/image?text=jvs+agencies+grandstand+marquee+durban+july+indoor+premium+dining&aspect=16:9&seed=1023',
  },
  {
    id: 'm24',
    name: 'Hive Marquee Experience',
    tier: 'Premium',
    price: 'From R5,000',
    priceValue: 5000,
    venue: 'Grandstand (Nursery)',
    description: 'The Hive Marquee Experience offers a buzzing atmosphere in the Grandstand Nursery area. A social hive of entertainment, gourmet food, and premium drinks.',
    includes: [
      'Grandstand nursery access',
      'Premium drinks package',
      'Gourmet food service',
      'Live entertainment',
      'Race viewing screens',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=hive+marquee+grandstand+durban+july+social+entertainment+buzzing&aspect=16:9&seed=1024',
  },
  {
    id: 'm25',
    name: 'One Stop Hospitality',
    tier: 'Premium',
    price: 'From R6,800',
    priceValue: 6800,
    venue: 'Grandstand Building (2nd Floor)',
    description: 'Premium hospitality on the second floor of the Grandstand Building with panoramic views of the racecourse. Air-conditioned suites with five-star dining.',
    includes: [
      'Air-conditioned indoor suite',
      'Full premium open bar',
      'Five-course gourmet lunch',
      'Afternoon high tea service',
      'Personal waitstaff',
      'Private betting terminals',
      'Race programme and tipping guide',
      'Private restrooms',
      'Live entertainment',
    ],
    image: 'https://api.a0.dev/assets/image?text=one+stop+hospitality+grandstand+durban+july+indoor+luxury+panoramic+view&aspect=16:9&seed=1025',
  },
  {
    id: 'm26',
    name: 'Sinayo Hospitality',
    tier: 'Premium',
    price: 'From R5,500',
    priceValue: 5500,
    venue: 'Grandstand Building (Silver Ring, 2nd Floor)',
    description: 'Sinayo Hospitality offers a polished Silver Ring experience on the second floor of the Grandstand Building. Premium hospitality with a refined touch.',
    includes: [
      'Silver Ring 2nd floor access',
      'Premium open bar',
      'Gourmet dining',
      'Race viewing position',
      'VIP restrooms',
      'Race programme',
    ],
    image: 'https://api.a0.dev/assets/image?text=sinayo+hospitality+silver+ring+grandstand+durban+july+refined+elegant&aspect=16:9&seed=1026',
  },
  {
    id: 'm27',
    name: 'Executive Concerts Marquee',
    tier: 'Ultra VIP',
    price: 'From R8,000',
    priceValue: 8000,
    venue: 'Greyville Racecourse',
    description: 'Hosted by Tbo Touch and Hope Mbhele, the Executive Concerts Marquee blends five-star hospitality with avant-garde fashion and bespoke entertainment.',
    includes: [
      'Five-star hospitality experience',
      'Exclusive lounges',
      'Curated food and cocktail bars',
      'Premium fashion moments',
      'Kabza De Small performance',
      'Nkosazana Daughter performance',
      'DJ Merlon and Stanky sets',
      'Surprise guest appearances',
      'VIP parking',
    ],
    capacity: 'Limited',
    image: 'https://api.a0.dev/assets/image?text=executive+concerts+marquee+durban+july+2025+tbo+touch+kabza+luxury+vip&aspect=16:9&seed=1027',
  },
  {
    id: 'm28',
    name: 'Perere Marquee',
    tier: 'VIP',
    price: 'From R3,500',
    priceValue: 3500,
    venue: 'Golf Course, Greyville Racecourse',
    description: 'A vibrant and contemporary marquee experience celebrating South African culture and lifestyle. Perere brings energy, style, and entertainment to the golf course precinct.',
    includes: [
      'Premium marquee access',
      'All-inclusive food and drinks',
      'Contemporary music and DJs',
      'Cultural activations',
      'Race viewing screens',
      'VIP restrooms',
    ],
    image: 'https://api.a0.dev/assets/image?text=perere+marquee+durban+july+vibrant+contemporary+cultural&aspect=16:9&seed=1028',
  },
  {
    id: 'm29',
    name: 'Mabeleni Marquee',
    tier: 'VIP',
    price: 'From R4,000',
    priceValue: 4000,
    venue: 'VIP Village, Greyville Racecourse',
    description: 'An exclusive marquee celebrating the very best of Mzansi lifestyle. Mabeleni combines luxury hospitality with authentic South African flair and world-class entertainment.',
    includes: [
      'All-inclusive premium experience',
      'Gourmet Mzansi cuisine',
      'Premium open bar',
      'Live entertainment and DJs',
      'Luxury ambiance',
      'VIP restrooms',
      'Fashion showcase',
    ],
    image: 'https://api.a0.dev/assets/image?text=mabeleni+marquee+durban+july+mzansi+luxury+gourmet&aspect=16:9&seed=1029',
  },
  {
    id: 'm30',
    name: 'One Stop Sport Hospitality',
    tier: 'Premium',
    price: 'From R5,500',
    priceValue: 5500,
    venue: 'Grandstand, Greyville Racecourse',
    description: 'Premier sports hospitality at the Greyville Racecourse. One Stop Sport Hospitality delivers professional event hosting with excellent racecourse views and premium catering.',
    includes: [
      'Grandstand marquee access',
      'Premium open bar',
      'Gourmet dining',
      'Excellent race viewing',
      'Betting facilities',
      'VIP restrooms',
      'Sports-themed entertainment',
    ],
    image: 'https://api.a0.dev/assets/image?text=one+stop+sport+hospitality+durban+july+grandstand+premium&aspect=16:9&seed=1030',
  },
  {
    id: 'm31',
    name: 'Regal Hospitality Marquee',
    tier: 'VVIP',
    price: 'From R6,500',
    priceValue: 6500,
    venue: 'VIP Village, Greyville Racecourse',
    description: 'An opulent marquee offering regal treatment and bespoke hospitality. Regal Hospitality combines sophisticated decor, fine dining, and entertainment in an atmosphere that exudes elegance.',
    includes: [
      'Regal-themed luxury experience',
      'Ultra-premium open bar',
      'Multi-course gourmet dining',
      'Champagne service',
      'Live entertainment',
      'Personal concierge',
      'VIP parking',
      'Gift bag on departure',
    ],
    image: 'https://api.a0.dev/assets/image?text=regal+hospitality+marquee+durban+july+opulent+elegant+luxury&aspect=16:9&seed=1031',
  },
];

// EVENTS - 14 Total
export const events: EventItem[] = [
  {
    id: 'e1',
    name: 'Hollywoodbets Durban July 2026',
    date: 'Saturday, 4 July 2026',
    time: '11:00 - 21:00',
    venue: 'Hollywoodbets Greyville Racecourse',
    location: 'Greyville, Durban',
    category: 'Race Day',
    description: 'Africa\'s Greatest Horse Racing Event. The 2026 theme is Country Allure, celebrating South Africa\'s vibrant heritage and diversity. Main stage lineup includes Mafikizolo, Lira, Hot Water, GoodLuck, DJ Dalootz, Lee Cole, and Sunset Sweatshop.',
    price: 'From R1,093',
    priceValue: 1093,
    highlights: [
      'Grade 1 horse race - 2200m',
      'Theme: Country Allure',
      'Approximately 45,000 attendees expected',
      'Mafikizolo, Lira, Hot Water, GoodLuck live',
      '31 marquees and VIP Marquee Village',
      'Fashion competition',
      'National anthem by Zolani Mahola',
    ],
    image: 'https://api.a0.dev/assets/image?text=hollywoodbets+durban+july+2025+horse+racing+greyville+marvels+of+mzansi&aspect=16:9&seed=2001',
  },
  {
    id: 'e2',
    name: 'Boomtown at Durban July 2026',
    date: 'Saturday, 4 July 2026',
    time: '11:00 - 21:00',
    venue: 'Boomtown Arena, Greyville Racecourse',
    location: 'Greyville, Durban',
    category: 'Concert',
    description: 'For 15 years, Boomtown has set the standard for premium entertainment at the Durban July. The 2026 lineup features Sjava, Cassper Nyovest, and Nasty C.',
    price: 'From R1,093',
    priceValue: 1093,
    highlights: [
      'Sjava live performance',
      'Cassper Nyovest live',
      'Nasty C live',
      'World-class sound and stage production',
      'VIP and VVIP packages available',
      'Food vendors and cash bars',
    ],
    image: 'https://api.a0.dev/assets/image?text=boomtown+durban+july+2025+sjava+cassper+nasty+c+stage&aspect=16:9&seed=2002',
  },
  {
    id: 'e3',
    name: 'Fact Durban Rocks July Edition 2025',
    date: 'Saturday, 4 July 2026',
    time: '12:00 - Late',
    venue: 'People\'s Park, Moses Mabhida Stadium',
    location: 'Durban CBD',
    category: 'Concert',
    description: 'Durban\'s biggest weekend concert at People\'s Park. A massive lineup featuring DJ Maphorisa, Kabza De Small, Cassper Nyovest, Kelvin Momo, Sjava, DJ Tira, Nkosazana Daughter, and many more.',
    price: 'From R250',
    priceValue: 250,
    highlights: [
      'DJ Maphorisa and Kabza De Small',
      'Cassper Nyovest, Sjava, Kelvin Momo',
      'DJ Tira, Nkosazana Daughter',
      'Zee Nxumalo, DJ Lag, Goldmax',
      'Duncan and Zakwe, Q Twins',
      'Dladla Mshunqski, Campmasters',
      'Massive marquee on site',
    ],
    image: 'https://api.a0.dev/assets/image?text=fact+durban+rocks+july+2025+peoples+park+moses+mabhida&aspect=16:9&seed=2003',
  },
  {
    id: 'e4',
    name: 'SoundLand Durban July After-Party',
    date: 'Saturday, 4 July 2026',
    time: '14:00 - Late',
    venue: 'Kings Park Stadium',
    location: 'Durban',
    category: 'After Party',
    description: 'The official Durban July afterparty at Kings Park Stadium. From 2pm until late, featuring Kabza De Small, Simmy, DJ Bongz, Blxckie, and more.',
    price: 'From R249',
    priceValue: 249,
    highlights: [
      'Kabza De Small headline set',
      'Simmy, DJ Bongz, Blxckie',
      'Dlala Thukzin, Nasty C, Oscar Mbo',
      'Young Stunna, Zee Nxumalo, Emtee',
      'VIP tents and chill lounges',
      'Gourmet food courts',
      'VVIP packages available',
    ],
    image: 'https://api.a0.dev/assets/image?text=soundland+durban+july+afterparty+2025+kings+park+stadium&aspect=16:9&seed=2004',
  },
  {
    id: 'e5',
    name: 'Rocket\'s Wonderland Lifestyle Fete',
    date: 'Sunday, 5 July 2026',
    time: 'TBA',
    venue: 'Munies Hockey Grounds, Botanical Gardens',
    location: 'Durban',
    category: 'Party',
    description: 'An opulent lifestyle fete fusing high fashion with entertainment, gourmet indulgence, and otherworldly design. Celebrates black excellence and urban sophistication.',
    price: 'TBA',
    priceValue: 0,
    highlights: [
      'Scorpion Kings (DJ Maphorisa and Kabza De Small)',
      'Dlala Thukzin live',
      'Oscar Mbo live',
      'High fashion showcase',
      'Gourmet food experience',
      'Premium lifestyle activations',
      'Black excellence celebration',
    ],
    image: 'https://api.a0.dev/assets/image?text=rockets+wonderland+lifestyle+fete+durban+july+2025&aspect=16:9&seed=2005',
  },
  {
    id: 'e6',
    name: 'Executive Concerts Marquee Day',
    date: 'Saturday, 4 July 2026',
    time: '11:00 - 21:00',
    venue: 'Greyville Racecourse',
    location: 'Greyville, Durban',
    category: 'Lifestyle',
    description: 'Hosted by Tbo Touch and Hope Mbhele, this five-star lifestyle and hospitality experience brings together Africa\'s top business leaders and cultural tastemakers.',
    price: 'From R8,000',
    priceValue: 8000,
    highlights: [
      'Hosted by Tbo Touch and Hope Mbhele',
      'Kabza De Small headline performance',
      'Nkosazana Daughter live',
      'DJ Merlon and Stanky',
      'Surprise guest performances',
      'Five-star hospitality',
      'Bespoke fashion and networking',
    ],
    image: 'https://api.a0.dev/assets/image?text=executive+concerts+marquee+2025+durban+july&aspect=16:9&seed=2006',
  },
  {
    id: 'e7',
    name: 'Durban July Main Stage Entertainment',
    date: 'Saturday, 4 July 2026',
    time: '12:00 - 20:00',
    venue: 'Hollywoodbets Greyville Racecourse (Main Stage)',
    location: 'Greyville, Durban',
    category: 'Concert',
    description: 'The official main stage entertainment at the Hollywoodbets Durban July 2026. A stellar SA music lineup featuring Mafikizolo, Lira, Hot Water, GoodLuck, DJ Dalootz, Lee Cole, and Sunset Sweatshop.',
    price: 'Included with entry',
    priceValue: 0,
    highlights: [
      'Mafikizolo timeless Afro-pop hits',
      'Lira South Africa\'s Diva of Soul',
      'Hot Water high-energy SA sounds',
      'GoodLuck electronic and live fusion',
      'DJ Dalootz',
      'Lee Cole dynamic pop vocals',
      'Sunset Sweatshop reggae and folk rock',
    ],
    image: 'https://api.a0.dev/assets/image?text=durban+july+2025+main+stage+mafikizolo+lira&aspect=16:9&seed=2007',
  },
  {
    id: 'e8',
    name: 'Halisi Afrique Marquee Experience',
    date: 'Saturday, 4 July 2026',
    time: '11:00 - 21:00',
    venue: 'VIP Village, Greyville Racecourse',
    location: 'Greyville, Durban',
    category: 'Lifestyle',
    description: 'Step into the vibrant energy of Halisi Afrique. A high-energy celebration of local culture, exotic flavours, and homegrown talent with all-inclusive premium hospitality.',
    price: 'From R6,000',
    priceValue: 6000,
    highlights: [
      'All-inclusive premium experience',
      'Gourmet food and exotic flavours',
      'Premium drinks and cocktails',
      'Luxury pampering stations',
      'Live entertainment and DJs',
      'Afro-luxury decor',
    ],
    image: 'https://api.a0.dev/assets/image?text=halisi+afrique+marquee+durban+july+2025&aspect=16:9&seed=2008',
  },
  {
    id: 'e9',
    name: 'Saso\'s Brunch Marquee',
    date: 'Saturday, 4 July 2026',
    time: '11:00 - 21:00',
    venue: 'Golf Course, Greyville Racecourse',
    location: 'Greyville, Durban',
    category: 'Lifestyle',
    description: 'The hottest marquee of 2024 returns even bigger. Curated by hip-hop star Lusaso Saso Ngcobo with Cradle of Humankind theme and 800 exclusive guests.',
    price: 'From R6,500',
    priceValue: 6500,
    highlights: [
      'Theme: Cradle of Humankind',
      '800 exclusive guests',
      'Curated by Lusaso Saso Ngcobo',
      'Mandisi Dyantyis headline',
      'Afro-futuristic fashion moments',
      'Gourmet culinary experiences',
      'Signature cocktail bars',
    ],
    image: 'https://api.a0.dev/assets/image?text=sasos+brunch+marquee+2025+durban+july&aspect=16:9&seed=2009',
  },
  {
    id: 'e10',
    name: 'Pegasus Lounge Trackside Experience',
    date: 'Saturday, 4 July 2026',
    time: '11:00 - 21:00',
    venue: 'Boomtown Trackside, Greyville Racecourse',
    location: 'Greyville, Durban',
    category: 'Lifestyle',
    description: 'In its fifteenth year, the Pegasus Lounge has cemented its status as the premier hospitality experience at the Durban July. Trackside positioning with ultra-premium service.',
    price: 'From R8,280',
    priceValue: 8280,
    highlights: [
      '15th anniversary edition',
      'Trackside premium positioning',
      'Ultra-premium open bar',
      'Five-course Chef Table menu',
      'Champagne welcome reception',
      'Celebrity appearances',
      'Personal concierge and valet parking',
    ],
    image: 'https://api.a0.dev/assets/image?text=pegasus+lounge+trackside+2025+durban+july&aspect=16:9&seed=2010',
  },
  {
    id: 'e11',
    name: 'Konka Big Tour: High Fashion Edition',
    date: 'Sunday, 5 July 2026',
    time: 'TBA',
    venue: 'TBA',
    location: 'Durban',
    category: 'Party',
    description: 'Konka presents The Big Tour High Fashion Edition for Durban July weekend. The iconic Soweto day club brings its signature energy\'s finest DJs and performers for an unforgettable celebration of music and culture.',
    price: 'TBA',
    priceValue: 0,
    highlights: [
      'Premium DJs and performers',
      'Exclusive party atmosphere',
      'VIP tables available',
      'Gourmet food and drinks',
      'Celebrity appearances',
      'High-energy entertainment',
    ],
    image: 'https://api.a0.dev/assets/image?text=konka+big+tour+high+fashion+sunday+durban+july+2025&aspect=16:9&seed=2011',
  },
  {
    id: 'e12',
    name: 'Any Given Sunday',
    date: 'Sunday, 5 July 2026',
    time: 'TBA',
    venue: 'TBA',
    location: 'Durban',
    category: 'Party',
    description: 'A star-studded Sunday soiree during the Durban July weekend. Any Given Sunday combines luxury hospitality with world-class entertainment and sophisticated social atmosphere.',
    price: 'TBA',
    priceValue: 0,
    highlights: [
      'Star-studded guest list',
      'World-class entertainment',
      'Luxury hospitality',
      'Premium cocktails and dining',
      'Intimate venue experience',
      'VIP packages available',
    ],
    image: 'https://api.a0.dev/assets/image?text=any+given+sunday+durban+july+2025&aspect=16:9&seed=2012',
  },
  {
    id: 'e13',
    name: 'Max Lifestyle Party',
    date: 'Sunday, 5 July 2026',
    time: 'TBA',
    venue: 'TBA',
    location: 'Durban',
    category: 'Lifestyle',
    description: 'An exclusive lifestyle celebration bringing together influencers, celebrities, and VIPs for an immersive experience combining fashion, food, music, and entertainment.',
    price: 'TBA',
    priceValue: 0,
    highlights: [
      'Exclusive VIP guest list',
      'Fashion moment activations',
      'Gourmet culinary experience',
      'World-class DJs and performers',
      'Premium lifestyle experience',
      'Social media moments',
    ],
    image: 'https://api.a0.dev/assets/image?text=max+lifestyle+party+sunday+durban+july+2025&aspect=16:9&seed=2013',
  },
  {
    id: 'e14',
    name: 'Lux Empire VIP All White Yacht Cruise',
    date: 'Sunday, 5 July 2026',
    time: 'TBA',
    venue: 'Durban Harbour Marina',
    location: 'Durban Waterfront',
    category: 'Lifestyle',
    description: 'An ultra-luxe Sunday finale to the Durban July weekend. The Lux Empire All White Yacht Cruise offers an exclusive sea-based experience with premium entertainment and gourmet dining.',
    price: 'From R2,500',
    priceValue: 2500,
    highlights: [
      'All-white luxury yacht',
      'Ocean cruise experience',
      'Scenic Durban coastline views',
      'Premium open bar',
      'Gourmet seafood dining',
      'Live DJ entertainment',
      'VIP cabin areas',
      'Champagne service',
    ],
    image: 'https://api.a0.dev/assets/image?text=lux+empire+all+white+yacht+cruise+sunday+durban+july+2025&aspect=16:9&seed=2014',
  },
  {
    id: 'e15',
    name: 'Road to Durban July Welcome Cocktail Party',
    date: 'Wednesday, 1 July 2026',
    time: '18:00 - 23:00',
    venue: 'The Oyster Box Hotel',
    location: 'Umhlanga Rocks',
    category: 'Lifestyle',
    description: 'Kick off Durban July week in style at this exclusive welcome cocktail party. Mingle with fashionistas, racing enthusiasts, and VIP guests as the city gears up for the greatest racing event.',
    price: 'From R500',
    priceValue: 500,
    highlights: [
      'Welcome cocktails and canapes',
      'Networking with VIP guests',
      'Fashion preview discussions',
      'Live jazz entertainment',
      'Ocean-view terrace setting',
      'Complimentary welcome drink',
    ],
    image: 'https://api.a0.dev/assets/image?text=welcome+cocktail+party+oyster+box+durban+july+week+2025+elegant&aspect=16:9&seed=2015',
  },
  {
    id: 'e16',
    name: 'Durban July Week Opening Night',
    date: 'Wednesday, 1 July 2026',
    time: '20:00 - 02:00',
    venue: 'Florida Road Venues',
    location: 'Florida Road, Durban',
    category: 'Party',
    description: 'Florida Road comes alive as Durban July week officially kicks off. Multiple venues along the iconic strip host special July-themed nights with top DJs and celebrity appearances.',
    price: 'From R150',
    priceValue: 150,
    highlights: [
      'Multiple Florida Road venues',
      'Top local DJs',
      'Celebrity appearances',
      'July-themed dress code',
      'Bar specials and promotions',
      'Pub crawl atmosphere',
    ],
    image: 'https://api.a0.dev/assets/image?text=florida+road+durban+nightlife+july+week+party+2025&aspect=16:9&seed=2016',
  },
  {
    id: 'e17',
    name: 'Durban July Fashion Preview and Designer Showcase',
    date: 'Thursday, 2 July 2026',
    time: '17:00 - 22:00',
    venue: 'Durban ICC',
    location: 'Durban CBD',
    category: 'Fashion',
    description: 'A glamorous evening showcasing the designers and fashion houses behind the Country Allure theme. Get a sneak peek at race day outfits and meet the creative talent shaping Durban July fashion.',
    price: 'From R350',
    priceValue: 350,
    highlights: [
      'Designer runway showcase',
      'Country Allure theme preview',
      'Meet-and-greet with designers',
      'Styling tips for race day',
      'Cocktail reception',
      'Fashion networking',
    ],
    image: 'https://api.a0.dev/assets/image?text=durban+july+fashion+preview+designer+showcase+2025+runway+models&aspect=16:9&seed=2017',
  },
  {
    id: 'e18',
    name: 'Thursday Night Pre-July Party',
    date: 'Thursday, 2 July 2026',
    time: '21:00 - 03:00',
    venue: 'Landmark Umhlanga',
    location: 'Umhlanga',
    category: 'Party',
    description: 'The pre-July party that sets the tone for the weekend. One of Durban hottest nightspots hosts an exclusive warm-up event with top DJs spinning Amapiano, Afro-house, and hip-hop.',
    price: 'From R200',
    priceValue: 200,
    highlights: [
      'Amapiano and Afro-house DJs',
      'VIP sections available',
      'Pre-July weekend warm-up',
      'Celebrity guest appearances',
      'Premium bottle service',
      'Late-night party vibes',
    ],
    image: 'https://api.a0.dev/assets/image?text=thursday+night+pre+july+party+umhlanga+club+2025+amapiano&aspect=16:9&seed=2018',
  },
  {
    id: 'e19',
    name: 'Mzansi Sip and Paint Experience',
    date: 'Thursday, 2 July 2026',
    time: '15:00 - 19:00',
    venue: 'The Pearls Mall',
    location: 'Umhlanga',
    category: 'Lifestyle',
    description: 'A creative afternoon celebrating the Country Allure theme through art and wine. Paint your own Durban July-inspired masterpiece while enjoying premium wines and cocktails.',
    price: 'From R450',
    priceValue: 450,
    highlights: [
      'Guided painting session',
      'Country Allure art theme',
      'Premium wine and cocktails',
      'Take home your artwork',
      'Social atmosphere',
      'Live acoustic music',
    ],
    image: 'https://api.a0.dev/assets/image?text=sip+and+paint+mzansi+art+durban+july+week+2025+wine&aspect=16:9&seed=2019',
  },
  {
    id: 'e20',
    name: 'Presidential Golf Day - Ballito Experience',
    date: 'Friday, 3 July 2026',
    time: '07:00 - 16:00',
    venue: 'Umhlali Country Club',
    location: 'Ballito, KZN',
    category: 'Lifestyle',
    description: 'The official Presidential Golf Day kicks off the Durban July Ballito Experience. A full day of golf, business networking, and premium hospitality hosted by Enterprise iLembe and DSAC.',
    price: 'By Invitation',
    priceValue: 0,
    highlights: [
      'Full 18-hole golf day',
      'Business networking platform',
      'Premium hospitality',
      'Enterprise iLembe initiative',
      'DSAC partnership',
      'Investment opportunity discussions',
      'Prize-giving ceremony',
    ],
    image: 'https://api.a0.dev/assets/image?text=presidential+golf+day+umhlali+country+club+ballito+durban+july+2025&aspect=16:9&seed=2020',
  },
  {
    id: 'e21',
    name: 'Durban July Eve: The Grand Pre-Party',
    date: 'Friday, 3 July 2026',
    time: '20:00 - 03:00',
    venue: 'Origin Nightclub',
    location: 'Durban North Beach',
    category: 'Party',
    description: 'The ultimate Friday night warm-up before race day. The biggest pre-party features a star-studded DJ lineup, premium bottle service, and the who is who of Durban July weekend.',
    price: 'From R300',
    priceValue: 300,
    highlights: [
      'Star-studded DJ lineup',
      'Amapiano and house music',
      'VIP and VVIP sections',
      'Premium bottle service',
      'Celebrity hosts',
      'Pre-party fashion moments',
      'Late-night energy',
    ],
    image: 'https://api.a0.dev/assets/image?text=durban+july+eve+grand+pre+party+nightclub+2025+amapiano+dj&aspect=16:9&seed=2021',
  },
  {
    id: 'e22',
    name: 'Umhlanga July Friday Sundowner',
    date: 'Friday, 3 July 2026',
    time: '16:00 - 22:00',
    venue: 'Lighthouse Bar Rooftop',
    location: 'Umhlanga',
    category: 'Lifestyle',
    description: 'A vibrant Friday sundowner experience as the Durban July weekend officially begins. Craft cocktails, live DJs, and ocean views set the scene for an unforgettable evening.',
    price: 'From R150',
    priceValue: 150,
    highlights: [
      'Rooftop ocean views',
      'Craft cocktails and local beers',
      'Live DJ sets',
      'Sundowner vibes',
      'Fashion pre-party atmosphere',
      'Social media moments',
    ],
    image: 'https://api.a0.dev/assets/image?text=umhlanga+friday+sundowner+rooftop+ocean+views+cocktails+2025&aspect=16:9&seed=2022',
  },
  {
    id: 'e23',
    name: 'July Jive: Amapiano Takeover',
    date: 'Friday, 3 July 2026',
    time: '22:00 - 04:00',
    venue: 'Cubana Florida Road',
    location: 'Florida Road, Durban',
    category: 'Party',
    description: 'Florida Road legendary Cubana hosts a massive Amapiano takeover on Durban July eve. Non-stop Amapiano, Gqom, and Afro-house from the finest DJs.',
    price: 'From R200',
    priceValue: 200,
    highlights: [
      'Non-stop Amapiano',
      'Gqom and Afro-house',
      'Local Durban DJs',
      'VIP booths available',
      'Late-night party',
      'Iconic Florida Road venue',
    ],
    image: 'https://api.a0.dev/assets/image?text=amapiano+takeover+cubana+florida+road+durban+july+eve+2025&aspect=16:9&seed=2023',
  },
  {
    id: 'e24',
    name: 'Ballito Experience Sunday Concert',
    date: 'Sunday, 5 July 2026',
    time: '12:00 - 20:00',
    venue: 'Beach Bums Westbrook',
    location: 'Ballito, KZN',
    category: 'Concert',
    description: 'The Durban July Ballito Experience wraps up with an invitation-only concert at Beach Bums. Featuring Nomfundo Moh, Msizi Shembe, Tbose, Ismail Abrahams, DJ Young and DJ Muntu.',
    price: 'By Invitation',
    priceValue: 0,
    highlights: [
      'Nomfundo Moh live performance',
      'Msizi Shembe live',
      'Tbose live',
      'Ismail Abrahams',
      'DJ Young and DJ Muntu',
      'Beachfront venue',
      'Fashion, food and live music',
    ],
    image: 'https://api.a0.dev/assets/image?text=durban+july+ballito+experience+beach+bums+concert+sunday+2025&aspect=16:9&seed=2024',
  },
  {
    id: 'e25',
    name: 'Sunday Recovery Brunch',
    date: 'Sunday, 5 July 2026',
    time: '10:00 - 15:00',
    venue: 'Oyster Box Hotel',
    location: 'Umhlanga Rocks',
    category: 'Lifestyle',
    description: 'Wind down after the big race day with a lavish Sunday recovery brunch. Bottomless mimosas, gourmet brunch, and ocean views provide the perfect reset before Sunday parties.',
    price: 'From R650',
    priceValue: 650,
    highlights: [
      'Bottomless mimosas and Bloody Marys',
      'Gourmet brunch buffet',
      'Ocean-view terrace',
      'Live acoustic music',
      'Relaxed recovery vibes',
      'Celebrity spotting',
    ],
    image: 'https://api.a0.dev/assets/image?text=sunday+recovery+brunch+oyster+box+durban+july+2025+mimosas+ocean&aspect=16:9&seed=2025',
  },
  {
    id: 'e26',
    name: 'Monday Farewell Pool Party',
    date: 'Monday, 6 July 2026',
    time: '11:00 - 18:00',
    venue: 'The Cabana Beach Resort',
    location: 'Umhlanga',
    category: 'Party',
    description: 'The final send-off of Durban July week. A chilled poolside party with cocktails, DJs, and good vibes before everyone heads home. The perfect way to close out an unforgettable weekend.',
    price: 'From R250',
    priceValue: 250,
    highlights: [
      'Poolside party vibes',
      'Craft cocktails and drinks',
      'Chill DJ sets',
      'Swimwear dress code',
      'Food vendors on site',
      'Farewell photo moments',
    ],
    image: 'https://api.a0.dev/assets/image?text=monday+farewell+pool+party+umhlanga+durban+july+2025+poolside&aspect=16:9&seed=2026',
  },
  {
    id: 'e27',
    name: 'Durban July Debrief Lunch',
    date: 'Monday, 6 July 2026',
    time: '12:00 - 16:00',
    venue: 'Havana Grill Umhlanga',
    location: 'Umhlanga',
    category: 'Lifestyle',
    description: 'Wrap up Durban July weekend with a relaxed lunch at one of Durban finest restaurants. Share stories, recap the best moments, and toast to another incredible Durban July.',
    price: 'A la carte',
    priceValue: 0,
    highlights: [
      'Premium a la carte dining',
      'Wine pairing options',
      'Relaxed atmosphere',
      'Weekend recap vibes',
      'Celebrity sightings',
      'No booking required',
    ],
    image: 'https://api.a0.dev/assets/image?text=durban+july+debrief+lunch+havana+grill+umhlanga+2025&aspect=16:9&seed=2027',
  },
];

// ACCOMMODATION
export const accommodation: AccommodationItem[] = [
  {
    id: 'a1',
    name: 'The Oyster Box Hotel',
    type: 'Luxury Hotel',
    area: 'Umhlanga Rocks',
    pricePerNight: 'From R6,500',
    priceValue: 6500,
    rating: 5,
    description: 'Durban\'s most iconic luxury hotel. Colonial elegance meets modern luxury with ocean views, a world-class spa, and fine dining.',
    amenities: ['Ocean-view rooms', 'Spa and wellness', 'Multiple restaurants', 'Infinity pool', 'Shuttle service', 'Concierge', '24hr room service'],
    distanceToVenue: '15 min drive',
    image: 'https://api.a0.dev/assets/image?text=oyster+box+hotel+umhlanga+luxury&aspect=16:9&seed=301',
  },
  {
    id: 'a2',
    name: 'The Beverly Hills Hotel',
    type: 'Luxury Hotel',
    area: 'Umhlanga Rocks',
    pricePerNight: 'From R4,800',
    priceValue: 4800,
    rating: 5,
    description: 'Legendary 5-star beachfront hotel offering timeless luxury and unrivalled ocean views.',
    amenities: ['Beachfront location', 'Full-service spa', 'Fine dining', 'Pool', 'Fitness centre', 'Shuttle service', 'Business centre'],
    distanceToVenue: '15 min drive',
    image: 'https://api.a0.dev/assets/image?text=beverly+hills+hotel+umhlanga+beachfront&aspect=16:9&seed=302',
  },
  {
    id: 'a3',
    name: 'Teremok Marine Lodge',
    type: 'Boutique Hotel',
    area: 'Marine Parade, Durban',
    pricePerNight: 'From R2,800',
    priceValue: 2800,
    rating: 4,
    description: 'Charming boutique lodge on Durban\'s Marine Parade. Walking distance to the Greyville Racecourse.',
    amenities: ['Walking distance to venue', 'Ocean views', 'Breakfast included', 'Free Wi-Fi', 'Secure parking', 'Garden terrace'],
    distanceToVenue: '5 min drive',
    image: 'https://api.a0.dev/assets/image?text=boutique+marine+lodge+durban&aspect=16:9&seed=303',
  },
  {
    id: 'a4',
    name: 'Quarters Hotel Florida Road',
    type: 'Boutique Hotel',
    area: 'Florida Road, Durban',
    pricePerNight: 'From R2,200',
    priceValue: 2200,
    rating: 4,
    description: 'Stylish boutique hotel on Durban\'s famous Florida Road. Steps from restaurants, bars, and after-party venues.',
    amenities: ['Prime Florida Road location', 'Pool', 'Restaurant and bar', 'Free Wi-Fi', 'Secure parking', 'Walking to nightlife'],
    distanceToVenue: '8 min drive',
    image: 'https://api.a0.dev/assets/image?text=boutique+hotel+florida+road+durban&aspect=16:9&seed=304',
  },
  {
    id: 'a5',
    name: 'Fairlight Beach House',
    type: 'Guest House',
    area: 'Umhlanga',
    pricePerNight: 'From R3,200',
    priceValue: 3200,
    rating: 5,
    description: 'Exclusive 5-star guest house in Umhlanga with panoramic ocean views, private pool, and personalised concierge service.',
    amenities: ['Ocean panoramic views', 'Private pool', 'Full breakfast', 'Concierge service', 'Secure parking', 'Lounge and bar', 'Walking to beach'],
    distanceToVenue: '18 min drive',
    image: 'https://api.a0.dev/assets/image?text=luxury+guest+house+umhlanga&aspect=16:9&seed=305',
  },
  {
    id: 'a6',
    name: 'Hartford House',
    type: 'Guest House',
    area: 'Morningside, Durban',
    pricePerNight: 'From R1,800',
    priceValue: 1800,
    rating: 4,
    description: 'Elegant guest house in the quiet suburb of Morningside. Beautiful gardens, warm hospitality, and easy racecourse access.',
    amenities: ['Peaceful suburb', 'Full English breakfast', 'Garden and pool', 'Secure parking', 'Free Wi-Fi', 'Laundry service'],
    distanceToVenue: '10 min drive',
    image: 'https://api.a0.dev/assets/image?text=elegant+guest+house+morningside+durban&aspect=16:9&seed=306',
  },
  {
    id: 'a7',
    name: 'Coastlands Musgrave Hotel',
    type: 'Luxury Hotel',
    area: 'Musgrave, Durban',
    pricePerNight: 'From R2,500',
    priceValue: 2500,
    rating: 4,
    description: 'Modern 4-star hotel in the heart of Musgrave. Close to shopping, dining, and easy racecourse access.',
    amenities: ['Modern rooms', 'Restaurant', 'Pool and gym', 'Free Wi-Fi', 'Shuttle available', 'Conference facilities'],
    distanceToVenue: '10 min drive',
    image: 'https://api.a0.dev/assets/image?text=modern+hotel+musgrave+durban&aspect=16:9&seed=307',
  },
  {
    id: 'a8',
    name: 'Riviera Villa Umhlanga',
    type: 'Villa',
    area: 'Umhlanga',
    pricePerNight: 'From R12,000',
    priceValue: 12000,
    rating: 5,
    description: 'Exclusive private villa sleeping 8-10 guests. Perfect for groups wanting privacy and luxury.',
    amenities: ['Sleeps 8-10', 'Private pool and garden', 'Full kitchen', 'Ocean views', 'Private chef available', 'Secure estate', 'Entertainment area'],
    distanceToVenue: '20 min drive',
    image: 'https://api.a0.dev/assets/image?text=luxury+private+villa+umhlanga&aspect=16:9&seed=308',
  },
  {
    id: 'a9',
    name: 'The Benjamin Aparthotel',
    type: 'Apartment',
    area: 'Umhlanga New Town Centre',
    pricePerNight: 'From R2,000',
    priceValue: 2000,
    rating: 4,
    description: 'Modern serviced apartments in Umhlanga. Self-catering flexibility with hotel-style amenities.',
    amenities: ['Self-catering kitchen', 'Rooftop pool', 'Gym', 'Free Wi-Fi', 'Underground parking', 'Walking to Gateway Mall'],
    distanceToVenue: '15 min drive',
    image: 'https://api.a0.dev/assets/image?text=modern+apartment+umhlanga&aspect=16:9&seed=309',
  },
];

// TRANSPORT
export const transport: TransportItem[] = [
  {
    id: 't1',
    name: 'July VIP Shuttle Service',
    type: 'Shuttle',
    price: 'From R350 pp',
    description: 'Luxury shuttle service between major hotels and Greyville Racecourse.',
    features: [
      'Air-conditioned luxury coaches',
      'Multiple departure times',
      'Pick-up from major hotels',
      'Return service until midnight',
      'Complimentary water on board',
    ],
    image: 'https://api.a0.dev/assets/image?text=luxury+shuttle+bus+vip+durban+july&aspect=16:9&seed=401',
  },
  {
    id: 't2',
    name: 'Executive Chauffeur Service',
    type: 'Chauffeur',
    price: 'From R3,500',
    description: 'Private chauffeur-driven luxury vehicle. Mercedes-Benz S-Class, BMW 7 Series, or Range Rover.',
    features: [
      'Choice of luxury vehicles',
      'Professional uniformed driver',
      'Door-to-door service',
      'Available for full day or transfers',
      'Complimentary champagne',
      'Wi-Fi on board',
    ],
    image: 'https://api.a0.dev/assets/image?text=luxury+chauffeur+mercedes+durban+july&aspect=16:9&seed=402',
  },
  {
    id: 't3',
    name: 'Helicopter Transfer',
    type: 'Helicopter',
    price: 'From R15,000',
    description: 'Arrive in ultimate style. Helicopter transfers to Greyville helipad.',
    features: [
      'Direct helipad at Greyville',
      'Transfers from King Shaka Airport',
      'Scenic coastal route available',
      'Up to 5 passengers',
      'VIP meet and greet',
      'Pre-bookable return flights',
    ],
    image: 'https://api.a0.dev/assets/image?text=helicopter+transfer+durban+coastline&aspect=16:9&seed=403',
  },
  {
    id: 't4',
    name: 'Luxury Car Hire',
    type: 'Luxury Car',
    price: 'From R5,000/day',
    description: 'Self-drive in style. Premium vehicles including Porsche, Ferrari, Lamborghini, and Bentley.',
    features: [
      'Exotic and luxury vehicle range',
      'Delivery to hotel/airport',
      'Full insurance included',
      'GPS navigation',
      'Roadside assistance',
      'Weekend packages available',
    ],
    image: 'https://api.a0.dev/assets/image?text=luxury+car+hire+porsche+ferrari&aspect=16:9&seed=404',
  },
];

// CONCIERGE SERVICES
export const conciergeServices: ConciergeService[] = [
  {
    id: 'c1',
    name: 'Personal Styling and Outfit Curation',
    category: 'Styling',
    price: 'From R2,500',
    description: 'Expert fashion stylists to nail the Country Allure theme. Includes outfit sourcing and accessories coordination.',
    features: [
      'Personal style consultation',
      'Country Allure theme expertise',
      'Outfit sourcing and procurement',
      'Hat and fascinator selection',
      'Accessories coordination',
      'Alteration arrangements',
    ],
    image: 'https://api.a0.dev/assets/image?text=personal+stylist+fashion+durban+july&aspect=16:9&seed=501',
  },
  {
    id: 'c2',
    name: 'Glam Squad Hair and Makeup',
    category: 'Grooming',
    price: 'From R1,800',
    description: 'Professional hair and makeup team to your hotel room. Get race-ready with a full glam experience.',
    features: [
      'In-room service at your hotel',
      'Professional makeup artist',
      'Hair styling and setting',
      'Touch-up kit provided',
      'Group packages available',
      'Mens grooming also available',
    ],
    image: 'https://api.a0.dev/assets/image?text=professional+hair+makeup+artist+durban+july&aspect=16:9&seed=502',
  },
  {
    id: 'c3',
    name: 'Professional Photography',
    category: 'Photography',
    price: 'From R3,000',
    description: 'Dedicated professional photographer capturing your Durban July experience. Includes edited digital gallery.',
    features: [
      'Dedicated photographer for the day',
      'Pre-event photoshoot',
      'Race day coverage',
      'Edited digital gallery 100 plus images',
      'Social media-ready content',
      'Drone photography available',
    ],
    image: 'https://api.a0.dev/assets/image?text=professional+photographer+durban+july&aspect=16:9&seed=503',
  },
  {
    id: 'c4',
    name: 'Personal Security Detail',
    category: 'Security',
    price: 'From R4,500',
    description: 'Discreet personal security for VIP attendees. Professional close protection officers.',
    features: [
      'Licensed security officers',
      'Discreet close protection',
      'Venue advance reconnaissance',
      'Vehicle security',
      'Available for full weekend',
      'Emergency response protocols',
    ],
    image: 'https://api.a0.dev/assets/image?text=professional+security+detail+bodyguard&aspect=16:9&seed=504',
  },
  {
    id: 'c5',
    name: 'VIP Personal Assistant',
    category: 'Personal Assistant',
    price: 'From R2,000/day',
    description: 'Your own personal assistant for the July weekend. Handles logistics and coordination seamlessly.',
    features: [
      'Restaurant and nightclub reservations',
      'Event ticket procurement',
      'Transport coordination',
      'Shopping assistance',
      'Itinerary planning',
      'Available via WhatsApp 24/7',
    ],
    image: 'https://api.a0.dev/assets/image?text=professional+personal+assistant+concierge&aspect=16:9&seed=505',
  },
  {
    id: 'c6',
    name: 'Private Chef and Catering',
    category: 'Catering',
    price: 'From R5,000',
    description: 'Private chef service for your villa or guest house. Pre-July dinners or full weekend meal plans.',
    features: [
      'Professional private chef',
      'Custom menu creation',
      'Shopping and preparation included',
      'Dietary requirements catered',
      'Breakfast, lunch and dinner options',
      'Cocktail party catering',
    ],
    image: 'https://api.a0.dev/assets/image?text=private+chef+gourmet+cooking+catering&aspect=16:9&seed=506',
  },
];

export const eventCategories = ['All', 'Race Day', 'Party', 'Fashion', 'Concert', 'Lifestyle', 'After Party'] as const;
export const accommodationTypes = ['All', 'Luxury Hotel', 'Boutique Hotel', 'Guest House', 'Villa', 'Apartment'] as const;
export const serviceTabs = ['Transport', 'Concierge'] as const;